import asyncio
import json
from pathlib import Path
import statistics

import typer
from rich.console import Console
from rich.table import Table

from fastagent.trace.replay import extract_chat_messages, load_trace_events, replay_messages

console = Console()


def trace_replay(
    trace_file: Path = typer.Option(..., "--trace-file", help="Trace JSONL file generated by your app."),
    event: str = typer.Option("chat_request", "--event", help="Trace event name to replay."),
    limit: int = typer.Option(0, "--limit", help="Optional max events to load (0 = all)."),
    base_url: str = typer.Option("", "--base-url", help="Target API base URL. If omitted, runs in dry-run mode."),
    endpoint: str = typer.Option("/chat", "--endpoint", help="Target chat endpoint."),
    concurrency: int = typer.Option(5, "--concurrency", help="Replay concurrency."),
    timeout: float = typer.Option(15.0, "--timeout", help="Per-request timeout in seconds."),
    output_json: Path | None = typer.Option(None, "--output-json", help="Optional JSON report path."),
) -> None:
    if concurrency <= 0:
        console.print("[red]Error:[/red] --concurrency must be > 0")
        raise typer.Exit(code=1)
    if timeout <= 0:
        console.print("[red]Error:[/red] --timeout must be > 0")
        raise typer.Exit(code=1)

    try:
        events = load_trace_events(trace_file, limit=limit if limit > 0 else None)
    except (FileNotFoundError, ValueError) as exc:
        console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(code=1)

    messages = extract_chat_messages(events, event_name=event)
    if not messages:
        console.print("[yellow]No replayable chat messages found in trace.[/yellow]")
        raise typer.Exit(code=1)

    plan_table = Table(title="FastAgent Trace Replay Plan")
    plan_table.add_column("Field", style="cyan")
    plan_table.add_column("Value", style="green")
    plan_table.add_row("trace_file", str(trace_file))
    plan_table.add_row("loaded_events", str(len(events)))
    plan_table.add_row("event_filter", event)
    plan_table.add_row("replayable_messages", str(len(messages)))
    plan_table.add_row("target", base_url.rstrip("/") + endpoint if base_url else "(dry-run)")
    console.print(plan_table)

    report: dict = {
        "trace_file": str(trace_file),
        "loaded_events": len(events),
        "event_filter": event,
        "replayable_messages": len(messages),
        "dry_run": not bool(base_url.strip()),
    }

    if not base_url.strip():
        preview = messages[:5]
        if preview:
            preview_table = Table(title="Message Preview")
            preview_table.add_column("#", style="cyan")
            preview_table.add_column("message", style="green")
            for idx, message in enumerate(preview, start=1):
                preview_table.add_row(str(idx), message)
            console.print(preview_table)
        console.print("[yellow]Dry run mode:[/yellow] provide --base-url to replay requests.")
        if output_json is not None:
            output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
            console.print(f"[green]Report written:[/green] {output_json}")
        return

    try:
        results = asyncio.run(
            replay_messages(
                base_url=base_url,
                endpoint=endpoint,
                messages=messages,
                concurrency=concurrency,
                timeout=timeout,
            )
        )
    except ImportError:
        console.print("[red]Error:[/red] httpx is required for trace replay. Install dependencies first.")
        raise typer.Exit(code=1)

    latencies = [item.latency_ms for item in results]
    success = [item for item in results if item.ok]
    failures = [item for item in results if not item.ok]

    p50 = statistics.median(latencies) if latencies else 0.0
    p95 = statistics.quantiles(latencies, n=20)[18] if len(latencies) >= 20 else max(latencies, default=0.0)
    p99 = statistics.quantiles(latencies, n=100)[98] if len(latencies) >= 100 else max(latencies, default=0.0)

    result_table = Table(title="FastAgent Trace Replay Result")
    result_table.add_column("Metric", style="cyan")
    result_table.add_column("Value", style="green")
    result_table.add_row("total", str(len(results)))
    result_table.add_row("success", str(len(success)))
    result_table.add_row("failed", str(len(failures)))
    result_table.add_row("success_rate", f"{(len(success) / len(results)) * 100:.2f}%" if results else "0.00%")
    result_table.add_row("latency_p50_ms", f"{p50:.2f}")
    result_table.add_row("latency_p95_ms", f"{p95:.2f}")
    result_table.add_row("latency_p99_ms", f"{p99:.2f}")
    result_table.add_row("latency_avg_ms", f"{statistics.mean(latencies):.2f}" if latencies else "0.00")
    console.print(result_table)

    report.update(
        {
            "dry_run": False,
            "target": base_url.rstrip("/") + endpoint,
            "total": len(results),
            "success": len(success),
            "failed": len(failures),
            "success_rate": (len(success) / len(results)) if results else 0.0,
            "latency_ms": {
                "p50": p50,
                "p95": p95,
                "p99": p99,
                "avg": statistics.mean(latencies) if latencies else 0.0,
            },
            "failures": [
                {
                    "index": item.index,
                    "status_code": item.status_code,
                    "error": item.error,
                    "message": item.message,
                }
                for item in failures[:25]
            ],
        }
    )

    if output_json is not None:
        output_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
        console.print(f"[green]Report written:[/green] {output_json}")

    if failures:
        raise typer.Exit(code=2)
