"""Deployment utilities."""

from fastagent.deployment.canary import (
    CanaryResult,
    CanaryThresholds,
    compare_canary_reports,
    load_report_json,
)
from fastagent.deployment.shadow import (
    ShadowSampleResult,
    ShadowSummary,
    execute_shadow_live,
    load_shadow_messages,
    simulate_shadow,
    summarize_shadow,
)
from fastagent.deployment.rollout import (
    RolloutDecision,
    RolloutState,
    apply_rollout_decision,
    decide_rollout,
    estimate_rollout_risk,
    evaluate_rollout_reports,
    load_rollout_state,
    parse_phase_plan,
    save_rollout_state,
)
from fastagent.deployment.autopilot_policy import (
    EnvironmentPolicy,
    PolicyEventDecision,
    decide_policy_event,
    load_environment_policy,
)
from fastagent.deployment.approval import (
    build_request_incident_key,
    ensure_request_expiry,
    find_request,
    get_or_create_pending_request,
    is_request_expired,
    is_target_deduped,
    load_approval_state,
    mark_request_expired,
    record_request_escalation,
    resolve_request,
    save_approval_state,
    should_escalate_request,
)
from fastagent.deployment.escalation import (
    build_escalation_payload,
    detect_channel,
    post_escalation_notification,
)
from fastagent.deployment.webhook import (
    build_deployment_payload,
    build_rollback_payload,
    post_signed_webhook,
    post_rollback_webhook,
    sign_payload,
)
from fastagent.deployment.traffic import (
    TrafficApplyPlan,
    build_argo_command,
    build_gateway_patch,
    build_gateway_patch_command,
    execute_command,
    load_rollout_decision_report,
    target_weight_from_report,
)

__all__ = [
    "CanaryThresholds",
    "CanaryResult",
    "load_report_json",
    "compare_canary_reports",
    "ShadowSampleResult",
    "ShadowSummary",
    "load_shadow_messages",
    "simulate_shadow",
    "execute_shadow_live",
    "summarize_shadow",
    "RolloutState",
    "RolloutDecision",
    "parse_phase_plan",
    "load_rollout_state",
    "save_rollout_state",
    "evaluate_rollout_reports",
    "estimate_rollout_risk",
    "decide_rollout",
    "apply_rollout_decision",
    "EnvironmentPolicy",
    "PolicyEventDecision",
    "load_environment_policy",
    "decide_policy_event",
    "load_approval_state",
    "save_approval_state",
    "build_request_incident_key",
    "find_request",
    "get_or_create_pending_request",
    "ensure_request_expiry",
    "is_request_expired",
    "is_target_deduped",
    "mark_request_expired",
    "should_escalate_request",
    "record_request_escalation",
    "resolve_request",
    "detect_channel",
    "build_escalation_payload",
    "post_escalation_notification",
    "build_deployment_payload",
    "build_rollback_payload",
    "sign_payload",
    "post_signed_webhook",
    "post_rollback_webhook",
    "TrafficApplyPlan",
    "load_rollout_decision_report",
    "target_weight_from_report",
    "build_argo_command",
    "build_gateway_patch",
    "build_gateway_patch_command",
    "execute_command",
]
