import typer

from fastagent.cli.commands.add_plugin import add_plugin
from fastagent.cli.commands.add_agent import add_agent
from fastagent.cli.commands.add_tool import add_tool
from fastagent.cli.commands.approval_list import approval_list
from fastagent.cli.commands.approval_resolve import approval_resolve
from fastagent.cli.commands.autopilot import autopilot
from fastagent.cli.commands.bench import run_bench
from fastagent.cli.commands.canary import canary_check
from fastagent.cli.commands.canary_shadow import canary_shadow
from fastagent.cli.commands.create import create_project
from fastagent.cli.commands.doctor import run_doctor
from fastagent.cli.commands.eval import eval_project
from fastagent.cli.commands.generate_signing_key import generate_signing_key
from fastagent.cli.commands.init_ci import init_ci
from fastagent.cli.commands.init_trust import init_trust
from fastagent.cli.commands.install_plugin import install_plugin
from fastagent.cli.commands.plugins import disable_plugin, enable_plugin, list_plugins
from fastagent.cli.commands.redteam import generate_redteam
from fastagent.cli.commands.rollback_webhook import rollback_webhook
from fastagent.cli.commands.rollout_apply import rollout_apply
from fastagent.cli.commands.rollout_controller import rollout_controller
from fastagent.cli.commands.remove_plugin import remove_plugin_cmd
from fastagent.cli.commands.run import run_project
from fastagent.cli.commands.sign_plugin import sign_plugin
from fastagent.cli.commands.trace_replay import trace_replay
from fastagent.cli.commands.verify_audit import verify_audit

app = typer.Typer(
    no_args_is_help=True,
    help="FastAgent: AI Agent Backend Framework for FastAPI.",
)

app.command("create", help="Create a new FastAgent backend project.")(create_project)
app.command("new", help="Alias for create.")(create_project)
app.command("run", help="Run a generated FastAgent project.")(run_project)
app.command("eval", help="Evaluate agent outputs from a dataset.")(eval_project)
app.command("add-tool", help="Add a tool plugin to an existing project.")(add_tool)
app.command("add-agent", help="Add an agent module to an existing project.")(add_agent)
app.command("doctor", help="Run FastAgent environment diagnostics.")(run_doctor)
app.command("bench", help="Benchmark a running FastAgent API endpoint.")(run_bench)
app.command("canary-check", help="Compare baseline vs candidate quality for canary rollout.")(canary_check)
app.command("canary-shadow", help="Run shadow traffic canary against baseline and candidate APIs.")(canary_shadow)
app.command("init-ci", help="Scaffold GitHub Actions eval-gate workflow and config.")(init_ci)
app.command("plugins", help="List configured plugins in a project.")(list_plugins)
app.command("install-plugin", help="Install a plugin from a registry with integrity checks.")(install_plugin)
app.command("init-trust", help="Initialize project trust policy for plugin installation.")(init_trust)
app.command("generate-signing-key", help="Generate Ed25519 keypair for plugin signing.")(generate_signing_key)
app.command("sign-plugin", help="Sign a plugin file and emit registry JSON snippet.")(sign_plugin)
app.command("enable-plugin", help="Enable a configured plugin.")(enable_plugin)
app.command("disable-plugin", help="Disable a configured plugin.")(disable_plugin)
app.command("add-plugin", help="Add or update a plugin in project manifest.")(add_plugin)
app.command("remove-plugin", help="Remove a plugin from project manifest.")(remove_plugin_cmd)
app.command("redteam", help="Generate synthetic red-team evaluation cases.")(generate_redteam)
app.command("trace-replay", help="Replay chat traces against an API endpoint.")(trace_replay)
app.command("verify-audit", help="Verify signed plugin audit log integrity.")(verify_audit)
app.command("rollback-webhook", help="Trigger signed rollback webhook for deployment automation.")(rollback_webhook)
app.command("rollout-controller", help="Automate phased canary rollout decisions from quality reports.")(rollout_controller)
app.command("rollout-apply", help="Apply rollout phase weight to Argo/Gateway traffic routing.")(rollout_apply)
app.command("autopilot", help="Run canary+shadow+rollout+traffic-apply in one command.")(autopilot)
app.command("approval-list", help="List manual approval requests generated by autopilot gate.")(approval_list)
app.command("approval-resolve", help="Resolve an approval request (approve/reject).")(approval_resolve)


def run() -> None:
    app()


if __name__ == "__main__":
    run()
